[package]
name = "ruth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_decimal = { version = "1.28.1", features = ["maths"] }
rust_decimal_macros = "1.28.1"
anyhow = "1.0.69"